<?php

return [
    'site_name' => 'eBook Publishing Agency',
    'default_title' => 'Publish Your Book. Get It Seen. - Professional Publishing Services',
    'default_description' => 'Helping authors write, publish, market and scale their books. Free strategy call + done-for-you publishing services.',
    'default_keywords' => 'book publishing, ghostwriting, book marketing, audiobook production, author services',
    'contact_email' => 'support@yourbrand.com',
    'contact_phone' => '+1 XXX XXX XXXX',
    'locations' => 'London, UK | New York, USA',
    'navigation' => [
        ['label' => 'Home', 'route' => 'home'],
        ['label' => 'Services', 'route' => 'services.index'],
        ['label' => 'About', 'route' => 'about'],
        ['label' => 'Blog', 'route' => 'blog'],
        ['label' => 'Contact', 'route' => 'contact'],
    ],
    'service_links' => [
        'book-publishing' => 'Book Publishing',
        'book-marketing' => 'Book Marketing',
        'book-writing' => 'Book Writing',
        'audiobook-services' => 'Audiobook Services',
        'book-editing' => 'Book Editing',
        'author-website-development' => 'Author Website Development',
        'book-printing' => 'Book Printing',
        'podcast-services' => 'Podcast Services',
        'book-illustration-design' => 'Book Illustration & Design',
    ],
    'hero' => [
        'headline' => 'Publish Your Book. Get It Seen.',
        'subheading' => 'Helping authors Write, Publish, Market and Scale their Books Without Wasting Time or Money, From Idea To Income.',
        'primary_cta' => 'Get a free strategy call',
        'secondary_cta' => 'Request a quote',
    ],
    'value_props' => [
        'title' => 'Stop Guessing Your Way Through Publishing',
        'intro' => 'We give you a clear, done-for-you path to:',
        'items' => [
            'Launch your book Like a pro',
            'Reach the right audience',
            'Turn your book into a long-term asset',
        ],
    ],
    'journey' => [
        'title' => 'Your Publishing Journey Starts Here',
        'steps' => [
            ['title' => 'Book Strategy Call (Free)', 'description' => 'We understand your idea, goals, and target audience.'],
            ['title' => 'Custom Execution Plan', 'description' => 'A clear roadmap for writing, publishing, and marketing.'],
            ['title' => 'Content Creation & Production', 'description' => 'We handle writing, editing, design, and formatting.'],
            ['title' => 'Publishing & Distribution', 'description' => 'Your book goes live on major platforms.'],
            ['title' => 'Growth & Promotion', 'description' => 'We help you gain visibility, traction, and sales.'],
        ],
        'cta' => 'Get a free strategy call',
    ],
    'testimonials' => [
        ['client_name' => 'James Carter', 'quote' => 'I had no idea where to start. They guided me step by step and got my book published quickly. It actually started getting visibility.', 'service' => 'Book Publishing'],
        ['client_name' => 'Emma Richardson', 'quote' => 'This wasn\'t just publishing, they helped position my book as a business asset. I\'ve already generated leads.', 'service' => 'Book Publishing'],
        ['client_name' => 'Daniel Brooks', 'quote' => 'My book wasn\'t selling before. Their marketing strategy improved visibility and conversions.', 'service' => 'Book Marketing'],
        ['client_name' => 'Olivia Bennett', 'quote' => 'They helped me expand into audiobooks and podcasting. It opened a new audience.', 'service' => 'Audiobook Services'],
    ],
    'faqs' => [
        ['question' => 'How do I publish a book if I have no experience?', 'answer' => 'You don\'t need prior experience. We guide you through the entire process from idea validation to publishing and marketing, so you don\'t feel lost at any stage.'],
        ['question' => 'How much does it cost to publish a book?', 'answer' => 'Costs vary depending on services like writing, editing, and marketing. We provide a customized plan based on your goals, so you only pay for what you actually need.'],
        ['question' => 'Can you help if I only have a rough idea and not a manuscript?', 'answer' => 'Yes. Our ghostwriting service helps turn your idea into a professionally written book ready for publishing.'],
        ['question' => 'Why isn\'t my self-published book getting sales?', 'answer' => 'Most books fail due to poor positioning, weak visibility, or lack of marketing. We fix this by planning targeted strategies, platform optimization, and audience-focused Marketing.'],
        ['question' => 'How long does it take to publish and launch a book?', 'answer' => 'It depends on the project, but most books are completed and launched within a few weeks to a few months.'],
        ['question' => 'Do I need an author website to succeed?', 'answer' => 'If you want long-term success and credibility, yes. An author website helps you build authority, collect leads, and promote your work effectively.'],
        ['question' => 'Can you convert my book into an audiobook?', 'answer' => 'Yes. We provide full audiobook production including narration, editing, and distribution setup.'],
        ['question' => 'What makes your service different from freelancers or platforms?', 'answer' => 'We don\'t just deliver tasks, we provide a complete strategy, execution, and growth system focused on real results, not just publishing.'],
    ],
    'services' => [
        'book-publishing' => [
            'name' => 'Book Publishing',
            'title' => 'Publish Your Book Professionally Without Stress',
            'headline' => 'Publishing a book is not just uploading files, it\'s about making your book market-ready, visible to your audience.',
            'subtitle' => 'We ensure your book is properly formatted, published, and distributed across major platforms.',
            'description' => 'Amazon Kindle Publishing, Paperback & Print Publishing, ISBN Setup, Professional Formatting, Meta data Optimization for Visibility, and Global Distribution Support.',
            'benefits' => ['No technical confusion', 'Professional publishing standards', 'Faster launch process', 'Optimized for sales visibility'],
            'cta' => 'Publish My Book',
        ],
        'book-marketing' => [
            'name' => 'Book Marketing',
            'title' => 'If Your Book Isn\'t Visible, It Won\'t Sell',
            'headline' => 'Most books fail not because of quality, but because of poor marketing.',
            'subtitle' => 'We help your book reach the right readers using data-driven marketing strategies.',
            'description' => 'Amazon SEO Optimization, Book Listing Enhancement, Social Media Promotion, Paid Advertising Campaigns, Audience Targeting Strategy, and Author Branding Support.',
            'benefits' => ['Increased visibility', 'Higher engagement', 'Better sales potential', 'Strong author presence'],
            'cta' => 'Increase My Book Sales',
        ],
        'book-writing' => [
            'name' => 'Book Writing',
            'title' => 'Turn Your Idea Into a Professionally Written Book',
            'headline' => 'You don\'t need to write a single word, we do it for you.',
            'subtitle' => 'Our professional writers turn your ideas into structured, engaging, publish-ready books.',
            'description' => 'Full Book Writing, Research & Structuring, Editing & Refinement, Industry-Standard Formatting, and Publishing Readiness.',
            'benefits' => ['Ideas become structured manuscripts', 'Editing is handled for you', 'Formatting stays consistent', 'Publish-ready delivery'],
            'cta' => 'Request a Quote',
        ],
        'audiobook-services' => [
            'name' => 'Audiobook Services',
            'title' => 'Turn Your Book Into a Powerful Audio Experience',
            'headline' => 'Audiobooks help you reach readers who prefer listening over reading.',
            'subtitle' => 'We create high-quality, professionally narrated audiobooks.',
            'description' => 'Professional Voice Narration, Audio Editing & Mastering, Audiobook Formatting, and Distribution Setup.',
            'benefits' => ['Professional narration', 'Clean audio editing', 'Platform-ready formatting', 'Distribution support'],
            'cta' => 'Create My Audiobook',
        ],
        'book-editing' => [
            'name' => 'Book Editing',
            'title' => 'Polish Your Manuscript to Perfection',
            'headline' => 'We refine your book so it reads clearly, professionally, and engagingly.',
            'subtitle' => 'Editing services that improve quality before publication.',
            'description' => 'Grammar Correction, Structure Improvement, Flow Enhancement, and Proofreading.',
            'benefits' => ['Cleaner copy', 'Stronger structure', 'Better flow', 'Careful proofreading'],
            'cta' => 'Request a quote',
        ],
        'author-website-development' => [
            'name' => 'Author Website Development',
            'title' => 'Build Your Personal Author Brand Online',
            'headline' => 'An author website builds credibility and helps you connect with readers globally.',
            'subtitle' => 'Custom websites designed to support author growth.',
            'description' => 'Custom Author Website, SEO Optimization, Mobile Responsive Design, and Lead Capture Forms.',
            'benefits' => ['Custom branding', 'Search visibility', 'Mobile responsive design', 'Lead capture support'],
            'cta' => 'Request a Quote',
        ],
        'book-printing' => [
            'name' => 'Book Printing',
            'title' => 'Put Your Book Into Readers\' Hands With Confidence',
            'headline' => 'Printing that keeps your book polished from file to finished copy.',
            'subtitle' => 'We help you prepare print-ready books with professional quality control.',
            'description' => 'Print-ready file preparation, layout checks, and production support for physical editions.',
            'benefits' => ['Print-ready files', 'Quality checks', 'Reliable production support', 'Distribution support'],
            'cta' => 'Request a Quote',
        ],
        'podcast-services' => [
            'name' => 'Podcast Services',
            'title' => 'Expand Your Reach Beyond Books',
            'headline' => 'Turn your book or ideas into engaging podcast content.',
            'subtitle' => 'Podcast support that helps you launch with clarity and confidence.',
            'description' => 'Podcast Setup, Audio Editing, Publishing Support, and Episode Structuring.',
            'benefits' => ['Launch support', 'Clear episode structure', 'Audio editing help', 'Publishing guidance'],
            'cta' => 'Launch My Podcast',
        ],
        'book-illustration-design' => [
            'name' => 'Book Illustration & Design',
            'title' => 'Give Your Book a Visual Identity That Stands Out',
            'headline' => 'Illustration and design support for covers, interiors, and brand polish.',
            'subtitle' => 'A consistent visual system that matches the quality of your book.',
            'description' => 'Cover concepts, illustration support, and design direction for a professional finish.',
            'benefits' => ['Standout visuals', 'Professional polish', 'Brand consistency', 'Reader trust'],
            'cta' => 'Request a Quote',
        ],
    ],
];