<?php

return [
    'site_name' => 'Pookybooks',
    'default_title' => 'Grow Your Brand to Success with World’s #1 E-Book Agency',
    'default_description' => 'An all-in-one ebook agency for you to build elite authority, attract high-ticket clients, and monetize your ideas. From writing to marketing, we are here till your ebook achieves your desired goals.',
    'default_keywords' => 'book publishing, ghostwriting, book marketing, audiobook production, author services',
    'contact_email' => 'support@yourbrand.com',
    'contact_phone' => '+1 XXX XXX XXXX',
    'locations' => 'London, UK | New York, USA',
    'navigation' => [
        ['label' => 'Home', 'route' => 'home'],
        ['label' => 'Services', 'route' => 'services.index'],
        ['label' => 'About', 'route' => 'about'],
        ['label' => 'Blog', 'route' => 'blog'],
        ['label' => 'Contact', 'route' => 'contact'],
    ],
    'service_links' => [
        'book-writing' => 'E-book Writing',
        'book-formatting' => 'E-book Formatting',
        'book-editing' => 'E-book Editing',
        'book-publishing' => 'E-book Publishing',
        'book-marketing' => 'E-book Marketing',
        'book-printing' => 'E-book Printing',
        'audiobook-services' => 'Audio Book',
        'author-website-development' => 'Author Website Development',
        'podcast-services' => 'Podcast Services',
        'book-illustration-design' => 'Book Illustration & Design',
        'cover-design' => 'Cover Design',
        'video-trailer' => 'Video Trailer',
    ],
    'hero' => [
        'headline' => 'Grow Your Brand to Success with World’s #1 E-Book Agency',
        'subheading' => 'An all-in-one ebook agency for you to build elite authority, attract high-ticket clients, and monetize your ideas. From writing to marketing, we are here till your ebook achieves your desired goals.',
        'primary_cta' => 'Get a free strategy call',
        'secondary_cta' => 'Request a quote',
    ],
    'value_props' => [
        'title' => 'Most Authors Are Just One Step Away from Earning Dollars',
        'intro' => 'We offer a done-for-you & complete path to monetize your ebooks:',
        'items' => [
            'Zero-friction ghostwriting & total confidentiality',
            '100% author equity to you',
            'Bespoke publishing with enterprise monetization',
        ],
    ],
    'journey' => [
        'title' => 'Publish Your Ebook in Just 5 Simple Steps',
        'steps' => [
            ['title' => 'Book a Free Strategy Call', 'description' => 'Talk with us to share your ideas, objectives, and target markets.'],
            ['title' => 'Custom Execution Plan', 'description' => 'We provide you with a complete roadmap to incentivize your ebook.'],
            ['title' => 'Content Creation & Production', 'description' => 'We produce an ebook as per your personality and tone.'],
            ['title' => 'Publishing', 'description' => 'Your book goes live on multiple major platforms.'],
            ['title' => 'Marketing', 'description' => 'Our experts get your visibility and sales from your ebook.'],
        ],
        'cta' => 'Talk to Our Experts for free',
    ],
    'testimonials' => [
        ['client_name' => 'James Carter', 'quote' => 'I felt totally lost since I had an amazing idea but didn’t know how to publish it. They took me through every step of the process and within a couple of weeks my book went live on Amazon and being discovered by readers. I was unable to do this without them.', 'service' => 'Book Publishing'],
        ['client_name' => 'Emma Richardson', 'quote' => 'This was not a service that helped me publish my book it was a plan to help my business. They showed me how to use my book to get customers and I have already gotten three big clients because of them. My book is really helping me get business.', 'service' => 'Book Publishing'],
        ['client_name' => 'Daniel Brooks', 'quote' => 'For months, my book didn’t sell at all. Then, experts at Pookybooks updated my Amazon listing, and a new marketing plan was put in place. After these changes, I sold 50 copies in just 30 days. It was a huge improvement, going from zero sales to 50 in such a short time. This made a big difference for my book.', 'service' => 'Book Marketing'],
    ],
    'faqs' => [
        ['question' => 'Does your agency handle everything, such as writing, editing, design, and marketing of ebooks?', 'answer' => 'Yes, we offer end-to-end services. Our experts cover the entire pipeline from ghostwriting and editing to cover design, formatting, and multi-channel promotion.'],
        ['question' => 'How much does it actually cost to hire an ebook agency in the USA?', 'answer' => 'It depends on your ebook and the agency rates. Most agencies get the job done between $1,500 and $6,000.'],
        ['question' => 'Will Pookybooks preserve my voice, or will the ebook sound like a generic template?', 'answer' => 'We’ll ensure that your ebook is specifically made in your tone. Our process is designed to distribute the books in your unique voice.'],
        ['question' => 'Do I own the rights to the ebook after the agency writes it?', 'answer' => 'Yes, you own 100% of the rights to your ebook. We use a signed contract to establish a trust between our agency and our clients.'],
        ['question' => 'What does ebook marketing actually include, and will it drive real sales?', 'answer' => 'Our ebook marketing services go well beyond a social post or two. We run targeted ad campaigns on Facebook, Google, and Amazon, execute book launch strategies, and connect your title with influencers to drive meaningful audience reach.'],
        ['question' => 'How long will it take from brief to a published, market-ready ebook?', 'answer' => 'Timelines depend on the length and complexity of the ebook. Talk to our experts to share your guides and learn about the ETA of publishing and market-ready ebooks.'],
        ['question' => 'How do I know if the agency\'s writers are actually qualified for my niche?', 'answer' => 'You can always request a portfolio with samples close to your topic. Rest assured that our portfolio is quite strong with versatility and mastery in your specific genre.'],
        ['question' => 'How long does marketing need to run before I see results?', 'answer' => 'Don\'t expect overnight numbers as ebook marketing is a compounding effort. We typically recommend investing at least 4–5 months into marketing campaigns before expecting measurable results.'],
    ],
    'services' => [
        'book-writing' => [
            'name' => 'E-book Writing',
            'title' => 'Give words to your thoughts',
            'headline' => 'You don\'t need to write a single word, we do it for you.',
            'subtitle' => 'Our expert ghostwriters turn your insights and frameworks into a high-converting ebook.',
            'description' => 'Full Book Writing, Research & Structuring, Editing & Refinement, Industry-Standard Formatting, and Publishing Readiness.',
            'benefits' => ['Ideas become structured manuscripts', 'Editing is handled for you', 'Formatting stays consistent', 'Publish-ready delivery'],
            'cta' => 'Request a Quote',
        ],
        'book-formatting' => [
            'name' => 'E-book Formatting',
            'title' => 'Ensure flawless design for easy comprehension',
            'headline' => 'Professional formatting makes all the difference in readability.',
            'subtitle' => 'Professional formatting to optimize the ebook for both digital and offline users.',
            'description' => 'Layout Design, Typography Selection, Image Placement, Table of Contents formatting, and cross-device testing.',
            'benefits' => ['Cleaner reading experience', 'Platform compliance', 'Professional presentation', 'Engaging layout'],
            'cta' => 'Request a Quote',
        ],
        'book-editing' => [
            'name' => 'E-book Editing',
            'title' => 'Final touches to perfect your script',
            'headline' => 'We refine your book so it reads clearly, professionally, and engagingly.',
            'subtitle' => 'Our editing services improve the quality of the ebook before it gets published.',
            'description' => 'Grammar Correction, Structure Improvement, Flow Enhancement, and Proofreading.',
            'benefits' => ['Cleaner copy', 'Stronger structure', 'Better flow', 'Careful proofreading'],
            'cta' => 'Request a quote',
        ],
        'book-publishing' => [
            'name' => 'E-book Publishing',
            'title' => 'Distribute your ebook for high traction',
            'headline' => 'Publishing a book is not just uploading files, it\'s about making your book market-ready.',
            'subtitle' => 'We provide a cost-effective way to list your ebooks on major platforms.',
            'description' => 'Amazon Kindle Publishing, Paperback & Print Publishing, ISBN Setup, Meta data Optimization, and Global Distribution.',
            'benefits' => ['No technical confusion', 'Professional publishing standards', 'Faster launch process', 'Optimized for sales visibility'],
            'cta' => 'Publish My Book',
        ],
        'book-marketing' => [
            'name' => 'E-book Marketing',
            'title' => 'Give your ebook the visibility it deserves',
            'headline' => 'Most books fail not because of quality, but because of poor marketing.',
            'subtitle' => 'Get more customers and revenue using our secret marketing strategies.',
            'description' => 'Amazon SEO Optimization, Book Listing Enhancement, Social Media Promotion, Paid Advertising Campaigns, and Audience Targeting.',
            'benefits' => ['Increased visibility', 'Higher engagement', 'Better sales potential', 'Strong author presence'],
            'cta' => 'Increase My Book Sales',
        ],
        'book-printing' => [
            'name' => 'E-book Printing',
            'title' => 'Put your ebook in the readers’ hands',
            'headline' => 'Printing that keeps your book polished from file to finished copy.',
            'subtitle' => 'We help you with the print-ready books for offline distribution.',
            'description' => 'Print-ready file preparation, layout checks, and production support for physical editions.',
            'benefits' => ['Print-ready files', 'Quality checks', 'Reliable production support', 'Distribution support'],
            'cta' => 'Request a Quote',
        ],
        'audiobook-services' => [
            'name' => 'Audio Book',
            'title' => 'Capture audience with a premium audio experience',
            'headline' => 'Audiobooks help you reach readers who prefer listening over reading.',
            'subtitle' => 'Get high-quality audiobooks to attract an audiophile audience.',
            'description' => 'Professional Voice Narration, Audio Editing & Mastering, Audiobook Formatting, and Distribution Setup.',
            'benefits' => ['Professional narration', 'Clean audio editing', 'Platform-ready formatting', 'Distribution support'],
            'cta' => 'Create My Audiobook',
        ],
        'author-website-development' => [
            'name' => 'Author Website Development',
            'title' => 'Brand yourself online for more perceptibility',
            'headline' => 'An author website builds credibility and helps you connect with readers globally.',
            'subtitle' => 'We will create custom author websites for authenticity and growth.',
            'description' => 'Custom Author Website, SEO Optimization, Mobile Responsive Design, and Lead Capture Forms.',
            'benefits' => ['Custom branding', 'Search visibility', 'Mobile responsive design', 'Lead capture support'],
            'cta' => 'Request a Quote',
        ],
        'podcast-services' => [
            'name' => 'Podcast Services',
            'title' => 'Scale your voice across multi-channels',
            'headline' => 'Turn your book or ideas into engaging podcast content.',
            'subtitle' => 'Share your voice on multiple networks for more reach.',
            'description' => 'Podcast Setup, Audio Editing, Publishing Support, and Episode Structuring.',
            'benefits' => ['Launch support', 'Clear episode structure', 'Audio editing help', 'Publishing guidance'],
            'cta' => 'Launch My Podcast',
        ],
        'book-illustration-design' => [
            'name' => 'Book Illustration & Design',
            'title' => 'Visualize your voice to stand out',
            'headline' => 'Illustration and design support for covers, interiors, and brand polish.',
            'subtitle' => 'We add bespoke graphics to lift the ebook quality.',
            'description' => 'Interior illustrations, infographic design, layout enrichment, and visual identity.',
            'benefits' => ['Standout visuals', 'Professional polish', 'Brand consistency', 'Reader trust'],
            'cta' => 'Request a Quote',
        ],
        'cover-design' => [
            'name' => 'Cover Design',
            'title' => 'Get scroll-stopping covers for attention',
            'headline' => 'Your cover is your first impression. Make it count.',
            'subtitle' => 'Our team designs custom covers to beat your competition.',
            'description' => 'Custom cover concepts, typography optimization, genre-specific design, and market research.',
            'benefits' => ['Scroll-stopping visuals', 'Genre-appropriate styling', 'Professional typography', 'Higher conversion rates'],
            'cta' => 'Request a Quote',
        ],
        'video-trailer' => [
            'name' => 'Video Trailer',
            'title' => 'Cinematic trailers for your social feeds',
            'headline' => 'Engage your audience with high-quality promotional video content.',
            'subtitle' => 'We build promotional video trailers to drive more traffic.',
            'description' => 'Script writing, video production, voiceover integration, and social media formatting.',
            'benefits' => ['High engagement', 'Social media ready', 'Professional production', 'Dynamic storytelling'],
            'cta' => 'Request a Quote',
        ],
    ],
    'portfolio' => [
        [
            'title' => 'A Coffee Shop at the End of Time',
            'category' => 'Cover Design',
            'description' => 'A complete cover design project with multiple high-quality mockups and visual concepts.',
            'thumbnail' => 'images/portfolio/project-1-thumb.webp',
            'images' => [
                'images/portfolio/project-1-thumb.webp',
                'images/portfolio/project-1-1.webp',
                'images/portfolio/project-1-2.webp',
                'images/portfolio/project-1-3.webp',
            ],
        ],
        [
            'title' => 'Ashes of Winter Lake',
            'category' => 'Cover Design',
            'description' => 'A stunning cover design project featuring high-quality visual concepts.',
            'thumbnail' => 'images/portfolio/project-2-thumb.webp',
            'images' => [
                'images/portfolio/project-2-thumb.webp',
                'images/portfolio/project-2-1.webp',
                'images/portfolio/project-2-2.webp',
                'images/portfolio/project-2-3.webp',
            ],
        ],
        [
            'title' => 'Broken Notes & Blue Skies',
            'category' => 'Cover Design',
            'description' => 'A visually captivating cover design project featuring multiple realistic mockups.',
            'thumbnail' => 'images/portfolio/project-3-thumb.webp',
            'images' => [
                'images/portfolio/project-3-thumb.webp',
                'images/portfolio/project-3-1.webp',
                'images/portfolio/project-3-2.webp',
                'images/portfolio/project-3-3.webp',
            ],
        ],
        [
            'title' => 'Echoes in Neon City',
            'category' => 'Cover Design',
            'description' => 'A vibrant, cyberpunk-inspired cover design project featuring high-quality mockups.',
            'thumbnail' => 'images/portfolio/project-4-thumb.webp',
            'images' => [
                'images/portfolio/project-4-thumb.webp',
                'images/portfolio/project-4-1.webp',
                'images/portfolio/project-4-2.webp',
                'images/portfolio/project-4-3.webp',
            ],
        ],
        [
            'title' => 'Letters Never Sent',
            'category' => 'Cover Design',
            'description' => 'An elegant and emotive cover design project with beautiful visual presentations.',
            'thumbnail' => 'images/portfolio/project-5-thumb.webp',
            'images' => [
                'images/portfolio/project-5-thumb.webp',
                'images/portfolio/project-5-1.webp',
                'images/portfolio/project-5-2.webp',
                'images/portfolio/project-5-3.webp',
            ],
        ],
        [
            'title' => 'Shadow of the Forgotten King',
            'category' => 'Cover Design',
            'description' => 'An epic fantasy cover design project capturing the atmosphere of a lost kingdom.',
            'thumbnail' => 'images/portfolio/project-6-thumb.webp',
            'images' => [
                'images/portfolio/project-6-thumb.webp',
                'images/portfolio/project-6-1.webp',
                'images/portfolio/project-6-2.webp',
                'images/portfolio/project-6-3.webp',
            ],
        ],
        [
            'title' => 'Stars Over Hollow Creek',
            'category' => 'Cover Design',
            'description' => 'A beautifully textured and atmospheric cover design showcasing deep visual storytelling.',
            'thumbnail' => 'images/portfolio/project-7-thumb.webp',
            'images' => [
                'images/portfolio/project-7-thumb.webp',
                'images/portfolio/project-7-1.webp',
                'images/portfolio/project-7-2.webp',
                'images/portfolio/project-7-3.webp',
            ],
        ],
        [
            'title' => 'The Girl Who Kept Secrets',
            'category' => 'Cover Design',
            'description' => 'A stunning and emotional cover design project featuring high-quality visual concepts.',
            'thumbnail' => 'images/portfolio/project-8-thumb.webp',
            'images' => [
                'images/portfolio/project-8-thumb.webp',
                'images/portfolio/project-8-1.webp',
                'images/portfolio/project-8-2.webp',
                'images/portfolio/project-8-3.webp',
            ],
        ],
        [
            'title' => 'The Last Summer Train',
            'category' => 'Cover Design',
            'description' => 'A beautiful and nostalgic cover design project featuring engaging visual mockups.',
            'thumbnail' => 'images/portfolio/project-9-thumb.webp',
            'images' => [
                'images/portfolio/project-9-thumb.webp',
                'images/portfolio/project-9-1.webp',
                'images/portfolio/project-9-2.webp',
                'images/portfolio/project-9-3.webp',
            ],
        ],
        [
            'title' => 'Whispers Beyond Midnight',
            'category' => 'Cover Design',
            'description' => 'A captivating and mysterious cover design project presenting rich visual mockups.',
            'thumbnail' => 'images/portfolio/project-10-thumb.webp',
            'images' => [
                'images/portfolio/project-10-thumb.webp',
                'images/portfolio/project-10-1.webp',
                'images/portfolio/project-10-2.webp',
                'images/portfolio/project-10-3.webp',
            ],
        ],
    ],
];
